// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // If we're on the client, always try to get the session.
    // getSession() is faster as it checks local storage first.
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
