// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuphudqargdosdrxznzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cGh1ZHFhcmdkb3Nkcnh6bnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzNDA0MTQsImV4cCI6MjA5NTkxNjQxNH0.QIUT7jK_MwwBM70I1cH1K3Cv3nNLV49E1HYHZzXFLTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});